### ISSUE TITLE
Deal with 'no visible binding for global variable' issue

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/apde#1]
When running a check on the package, the following notes are made:
kc_geocode: no visible binding for global variable 'addressType'
  kc_geocode: no visible binding for global variable 'score'
  Undefined global functions or variables:
    addressType score

Proposed solutions seem to be to import rlang .data but that didn't completely solve the issue (https://dplyr.tidyverse.org/articles/programming.html#eliminating-r-cmd-check-notes-1). Maybe need to tinker with this approach a bit more.

**Comment by dcaseykc** [comment]
you can just do something like `addressType <- NULL` at the top of the function with the global variable grumpies
